INSERT INTO PROVEEDOR (RUTPROVEEDOR, COMUNA, DIRECCION, NOMBREPROVEEDOR)
VALUES ('15649586-K', 'Temuco', 'Olimpia 958', 'Eduardo Garrido');
INSERT INTO PROVEEDOR (RUTPROVEEDOR, COMUNA, DIRECCION, NOMBREPROVEEDOR)
VALUES ('14986594-9', 'Santiago', 'Vasco da Gama 784', 'Daniela Jara');
INSERT INTO PROVEEDOR (RUTPROVEEDOR, COMUNA, DIRECCION, NOMBREPROVEEDOR)
VALUES ('14586425-0', 'Concepción', 'Carrera 458', 'Esteban Salinas');

INSERT INTO ITEM (CODPRODUCTO, NOMBREPRODUCTO, PRECIO, STOCK, RUTPROVEEDOR)
VALUES (1, 'Sandalia', 9990, 150, '15649586-K');
INSERT INTO ITEM (CODPRODUCTO, NOMBREPRODUCTO, PRECIO, STOCK, RUTPROVEEDOR)
VALUES (2, 'Toalla', 4990, 401, '14986594-9');
INSERT INTO ITEM (CODPRODUCTO, NOMBREPRODUCTO, PRECIO, STOCK, RUTPROVEEDOR)
VALUES (3, 'Polera niño', 10090, 97, '14586425-0');

-- Exclusive of this particular data input
ALTER SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 3;
SELECT HIBERNATE_SEQUENCE.nextval FROM DUAL;
ALTER SEQUENCE HIBERNATE_SEQUENCE INCREMENT BY 1;
